//------------------------------------------------------------------------
// Copyright(c) 2024 Nagater Networks.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"vbanpluginbundle.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"vbanpluginbundle VST3 (64Bit)"
#else
#define stringFileDescription	"vbanpluginbundle VST3"
#endif
#define stringCompanyName		"Nagater Networks\0"
#define stringLegalCopyright	"Copyright(c) 2024 Nagater Networks."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
